export const mobileAction = {
  POST_NUMBER: "mobile/POST_NUMBER",
  POST_NUMBER_SUCCESS: "mobile/POST_NUMBER_SUCCESS",
  POST_NUMBER_FAILED: "mobile/POST_NUMBER_FAILED",
};

export const otpVerificationAction = {
  POST_OTP: "otp/POST_OTP",
  POST_OTP_SUCCESS: "otp/POST_OTP_SUCCESS",
  POST_OTP_FAILED: "otp/POST_OTP_FAILED",
};

export const appAction = {
  SHOW_ALERT: "app/SHOW_ALERT",
};


export const restaurantdata = {
 GET_RESTAURANT_DATA_REQUESTED : "GET_RESTAURANT_DATA_REQUESTED",
 GET_RESTAURANT_DATA_SUCCESS : "GET_RESTAURANT_DATA_SUCCESS",
 GET_RESTAURANT_DATA_FAILED : "GET_RESTAURANT_DATA_FAILED",
};

// **************getMenuData*****************
export const menuData = {
  GET_MENU_REQUESTED: 'GET_MENU_REQUESTED',
  GET_MENU_SUCCESS : 'GET_MENU_SUCCESS',
  GET_MENU_FAILED : "GET_MENU_FAILED",
}
